#!/usr/bin/env bash
set -euo pipefail

if ! [[ "$1" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "error: invalid version format"
    echo "expected 'vX.Y.Z'"
    exit 1
fi

docker buildx build --platform linux/amd64 --build-arg SIREN_SITE_VERSION="${1#v}" -t "site:$1" -t "registry.digitalocean.com/reg-xiren/site:$1" .
docker push "registry.digitalocean.com/reg-xiren/site:$1"
./scripts/registry-cleanup
